# Hunar Internship - Task 4

## 📌 Objective
The objective of this task is to create a NumPy matrix from user input and calculate the sum of its diagonal elements using a loop.

## 🛠️ Tools Used
- Python
- NumPy
- Jupyter Notebook

## 📚 Concepts Covered
- NumPy Arrays
- User Input
- Loops
- Matrix Operations

In [3]:
import numpy as np

## Step 1: Enter Matrix Order

The user enters the size of the square matrix.

In [1]:
n = int(input("Enter the order of the matrix: "))

Enter the order of the matrix:  4


## Step 2: Enter Matrix Elements

The user enters all the elements of the matrix row by row.

In [4]:
matrix = []

print("Enter the matrix elements:")

for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)

matrix = np.array(matrix)

print("\nMatrix:")
print(matrix)

Enter the matrix elements:


 1 2 3 4
 5 6 7 8
 9 10 11 12
 13 14 15 16



Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Step 3: Calculate Sum of Diagonal Elements

Using a loop, calculate the sum of the main diagonal elements of the matrix.

In [5]:
diagonal_sum = 0

for i in range(n):
    diagonal_sum += matrix[i][i]

print("Sum of diagonal elements =", diagonal_sum)

Sum of diagonal elements = 34
